var TEAM_OWNERS = {
   'Montreal'       :  [ 'Kevin', false,'$14']
  ,'Tampa Bay'      :  [ 'Alex', false,'$18']
  ,'Florida'        :  [ 'Kevin', false,'$8']
  ,'Ottawa'         :  [ 'Duncan', false,'$2']
  ,'Detroit'        :  [ 'Alex', false,'$6']
  ,'Boston'         :  [ 'Mike', true,'Favorite']
  ,'Buffalo'        :  [ 'Matt', true,'Favorite']
  ,'Toronto'        :  [ 'Alex', true,'Favorite']
  ,'NY Islanders'   :  [ 'Mike', false,'$9']
  ,'NY Rangers'     :  [ 'Duncan', false,'$13']
  ,'Washington'     :  [ 'Matt', false,'$20']
  ,'Pittsburgh'     :  [ 'Mike', false,'$19']
  ,'Philadelphia'   :  [ 'Andy', false,'$3']
  ,'New Jersey'     :  [ 'Matt', false,'$1']
  ,'Carolina'       :  [ 'Alex', false,'$0']
  ,'Columbus'       :  [ 'Kevin', true,'Favorite']
  ,'Dallas'         :  [ 'Matt', false,'$8']
  ,'Nashville'      :  [ 'Alex', false,'$16']
  ,'St. Louis'      :  [ 'Andy', false,'$18']
  ,'Winnipeg'       :  [ 'Kevin', false,'$1']
  ,'Minnesota'      :  [ 'Mike', false,'$7']
  ,'Chicago'        :  [ 'Duncan', false,'$20']
  ,'Colorado'       :  [ 'Mike', false,'$5']
  ,'San Jose'       :  [ 'Andy', true,'Favorite']
  ,'Vancouver'      :  [ 'Matt', false,'$1']
  ,'Arizona'        :  [ 'Kevin', false,'$2']
  ,'Los Angeles'    :  [ 'Duncan', true,'Favorite']
  ,'Edmonton'       :  [ 'Duncan', false,'$4']
  ,'Anaheim'        :  [ 'Andy', false,'$16']
  ,'Calgary'        :  [ 'Andy', false,'$3']
};
