var TEAM_OWNERS = {
   'MTL' :[ 'Andy' , false ,'$3' ]
  ,'TBL' :[ 'Alex' , false , '$23' ]
  ,'FLO' :[ 'Matt', false ,'$9']
  ,'OTT' :[ 'Alex' , false , '$0']
  ,'DET' :[ 'Andy' , false , '$0']
  ,'BOS' :[ 'Mike' , true , 'Favorite' ]
  ,'BUF' :[ 'Mike' , false , '$3' ]
  ,'TOR' :[ 'Alex' , true , 'Favorite' ]
  ,'NYI' :['Duncan' , false , '$5']
  ,'NYR' :[ 'Alex', false , '$1']
  ,'WSH' :[ 'Andy', false , '$18']
  ,'PIT' :['Duncan' , false , '$16']
  ,'PHI' :[ 'Duncan', false ,'$9' ]
  ,'NJD' :[ 'Mike', false, '$4']
  ,'CAR' :[ 'Matt' , false ,' $5' ]
  ,'CBJ' :[ 'Kevin', true , 'Favorite']
  ,'DAL' :[ 'Duncan', false ,'$7' ]
  ,'NSH' :['Mike' , false,  '$21']
  ,'STL' :[ 'Andy', false , '$12']
  ,'WPJ' :['Matt' , false , '$22']
  ,'MIN' :['Duncan', false, '$6']
  ,'CHI' :['Mike', false ,'$5']
  ,'COL' :[ 'Matt' , false , '$6' ]
  ,'SJS' :[ 'Andy' , true , 'Favorite']
  ,'VAN' :[ 'Alex' , false , '$2' ]
  ,'ARI' :[ 'Matt', false , '$1']
  ,'LAK' :[ 'Duncan' , true , 'Favorite']
  ,'EDM' :[ 'Andy', false , '$10']
  ,'ANA' :[ 'Alex' , false , '$17']
  ,'CGY' :[ 'Mike', false , '$10']
  ,'VGK' :['Matt' , true , 'Favorite' ]
};
