var TEAM_OWNERS = {
   'Montreal'       :   'Andy'
  ,'Tampa Bay'      :   'Kevin'
  ,'Florida'        :   'Alex'
  ,'Ottawa'         :   'Mike'
  ,'Detroit'        :   'Alex'
  ,'Boston'         :   'Mike'
  ,'Buffalo'        :   'Matt'
  ,'Toronto'        :   'Alex'
  ,'NY Islanders'   :   'Kevin'
  ,'NY Rangers'     :   'Mike'
  ,'Washington'     :   'Matt'
  ,'Pittsburgh'     :   'Duncan'
  ,'Philadelphia'   :   'Andy'
  ,'New Jersey'     :   'Matt'
  ,'Carolina'       :   'Duncan'
  ,'Columbus'       :   'Kevin'
  ,'Dallas'         :   'Duncan'
  ,'Nashville'      :   'Kevin'
  ,'St. Louis'      :   'Andy'
  ,'Winnipeg'       :   'Alex'
  ,'Minnesota'      :   'Mike'
  ,'Chicago'        :   'Duncan'
  ,'Colorado'       :   'Mike'
  ,'San Jose'       :   'Andy'
  ,'Vancouver'      :   'Matt'
  ,'Arizona'        :   'Kevin'
  ,'Los Angeles'    :   'Duncan'
  ,'Edmonton'       :   'Andy'
  ,'Anaheim'        :   'Matt'
  ,'Calgary'        :   'Alex'
};
