var TEAM_OWNERS = {
                      'Colombia' : 'Kevin'
                      ,'Côte d\'Ivoire' : 'Andy'
                      ,'Japan' : 'Matt'
                      ,'England' : 'Mike'
                      ,'United States' : 'Andy'
                      ,'Ghana' : 'Andy'
                      ,'Portugal' : 'Kevin'
                      ,'Netherlands' : 'Andy'
                      ,'Chile' : 'Kevin'
                      ,'Australia' : 'Matt'
                      ,'Argentina' : 'Kevin'
                      ,'Iran' : 'Matt'
                      ,'Brazil' : 'Matt'
                      ,'Cameroon' : 'Kevin'
                      ,'Italy' : 'Matt'
                      ,'Uruguay' : 'Kevin'
                      ,'Nigeria' : 'Matt'
                      ,'Germany' : 'Mike'
                      ,'Belgium' : 'Andy'
                      ,'Russia' : 'Kevin'
                      ,'Algeria' : 'Matt'
                      ,'Ecuador' : 'Andy'
                      ,'Honduras' : 'Kevin'
                      ,'Spain' : 'Mike'
                      ,'Mexico' : 'Mike'
                      ,'Croatia' : 'Andy'
                      ,'Greece' : 'Mike'
                      ,'Costa Rica' : 'Andy'
                      ,'Korea Republic' : 'Mike'
                      ,'France' : 'Matt'
                      ,'Bosnia-Herzegovina' : 'Mike'
                      ,'Switzerland' : 'Mike'
};
